const SEATWISE_SUPABASE_URL='https://axhyzxuclxjojhtispqp.supabase.co';
const SEATWISE_SUPABASE_KEY='sb_publishable_6biluj5Hfmtz3tplDaO6qw_ektOIx3h';
const seatwiseDb=supabase.createClient(SEATWISE_SUPABASE_URL,SEATWISE_SUPABASE_KEY);
const SEATWISE_SESSION_TIMEOUT=30*60*1000;
function setSeatwiseSession(user){const now=Date.now();sessionStorage.setItem('seatwiseUser',JSON.stringify({id:user.id||null,name:user.name,phone:user.phone,school_id:user.school_id||null,school_name:user.school_name||null,school_logo_url:user.school_logo_url||null,issuedAt:now,lastActivity:now,expiresAt:now+SEATWISE_SESSION_TIMEOUT}))}
function getSeatwiseSession(){try{const raw=sessionStorage.getItem('seatwiseUser');if(!raw)return null;const u=JSON.parse(raw);if(!u||!u.school_id)return null;const now=Date.now();if(u.expiresAt&&now>=u.expiresAt){clearSeatwiseSession();return null}if(!u.lastActivity||!u.expiresAt){u.lastActivity=now;u.expiresAt=now+SEATWISE_SESSION_TIMEOUT;sessionStorage.setItem('seatwiseUser',JSON.stringify(u))}return u}catch(e){clearSeatwiseSession();return null}}
function touchSeatwiseSession(){try{const raw=sessionStorage.getItem('seatwiseUser');if(!raw)return;const u=JSON.parse(raw);if(!u||!u.school_id)return;const now=Date.now();if(u.expiresAt&&now>=u.expiresAt){clearSeatwiseSession();location.replace('index.html');return}u.lastActivity=now;u.expiresAt=now+SEATWISE_SESSION_TIMEOUT;sessionStorage.setItem('seatwiseUser',JSON.stringify(u))}catch(e){clearSeatwiseSession()}}
function clearSeatwiseSession(){sessionStorage.removeItem('seatwiseUser');sessionStorage.removeItem('seatwiseAdmin')}
function requireSeatwiseLogin(){const u=getSeatwiseSession();if(!u){location.replace('index.html');return null}touchSeatwiseSession();return u}
function seatwiseLogout(){clearSeatwiseSession();location.replace('index.html')}
(function(){const file=(location.pathname.split('/').pop()||'index.html').toLowerCase();if(file==='index.html'){clearSeatwiseSession();return}if(getSeatwiseSession()){let lastTouch=0;['click','keydown','pointerdown','touchstart','scroll'].forEach(evt=>document.addEventListener(evt,()=>{const now=Date.now();if(now-lastTouch>30000){lastTouch=now;touchSeatwiseSession()}},{passive:true,capture:true}));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')touchSeatwiseSession()});window.addEventListener('pageshow',()=>{if(!getSeatwiseSession())location.replace('index.html')});setInterval(()=>{if(!getSeatwiseSession())location.replace('index.html')},60000)}})();
async function logActivity(action,details={},userId=null){const u=getSeatwiseSession(),id=userId||u?.id||null;const{error}=await seatwiseDb.from('activity_logs').insert({user_id:id,action,details});if(error)console.error('Activity log error:',error)}
function getCurrentAcademicSession(date=new Date()){const y=date.getFullYear(),m=date.getMonth(),s=m>=3?y:y-1;return `${s}-${s+1}`}
async function ensureCurrentAcademicSession(){const n=getCurrentAcademicSession(),y=+n.slice(0,4);const{error}=await seatwiseDb.from('academic_sessions').upsert({session_name:n,start_date:`${y}-04-01`,end_date:`${y+1}-03-31`},{onConflict:'session_name'});if(error)console.error('Academic session error:',error);return n}
async function initializeAcademicSessionUI(){const h=document.querySelector('.saved-head');if(!h)return;const d=h.querySelector('p');if(d)d.textContent=`Current Session: ${await ensureCurrentAcademicSession()}`}

// Shared navigation is rendered from the dedicated navigation component.
(function(){
  const nav=document.querySelector('.nav');
  if(!nav)return;
  nav.replaceChildren();
  nav.classList.add('seatwise-nav-loading');
  const label=document.createElement('div');label.className='nav-label';label.textContent='Main Menu';nav.appendChild(label);
  const file=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const items=[['dashboard.html','▦','Dashboard'],['students.html','♙','Classes & Sections'],['rooms.html','⌂','Rooms'],['subjects-v2.html','◈','Subjects'],['exam-planner.html','◫','Exam Planner'],['exams.html','▤','Exams']];
  items.forEach(([href,icon,text])=>{const a=document.createElement('a');a.href=href;if(href===file)a.className='active';const s=document.createElement('span');s.className='nav-icon';s.textContent=icon;a.append(s,document.createTextNode(text));nav.appendChild(a)});
  const group=document.createElement('div');group.className='nav-settings-group';
  const settings=document.createElement('a');settings.href='settings.html';settings.className='nav-settings-toggle';if(file==='settings.html'||file==='user-management.html'||file==='history.html')settings.classList.add('active');const si=document.createElement('span');si.className='nav-icon';si.textContent='⚙';const sa=document.createElement('span');sa.className='nav-settings-arrow';sa.textContent='⌄';settings.append(si,document.createTextNode('Settings'),sa);group.appendChild(settings);
  const sub=document.createElement('div');sub.className='nav-submenu';[['user-management.html','♙','User Management'],['history.html','◷','History']].forEach(([href,icon,text])=>{const a=document.createElement('a');a.href=href;if(href===file)a.className='active';const s=document.createElement('span');s.className='nav-icon';s.textContent=icon;a.append(s,document.createTextNode(text));sub.appendChild(a)});group.appendChild(sub);nav.appendChild(group);
  if(file==='settings.html'||file==='user-management.html'||file==='history.html')group.classList.add('open');
  settings.addEventListener('click',e=>{if(!group.classList.contains('open')){e.preventDefault();group.classList.add('open')}});
  const style=document.createElement('style');style.textContent='.nav-settings-group{margin:0}.nav-settings-toggle{position:relative}.nav-settings-arrow{margin-left:auto;font-size:14px;transition:transform .18s ease}.nav-settings-group.open .nav-settings-arrow{transform:rotate(180deg)}.nav-submenu{display:none;padding:2px 0 8px}.nav-settings-group.open .nav-submenu{display:block}.nav-submenu a{padding-left:58px!important;font-size:14px!important;min-height:40px!important}.nav-submenu a .nav-icon{font-size:13px!important}.nav-submenu a.active{background:rgba(255,255,255,.16)!important}.nav-settings-group>a.active{background:rgba(255,255,255,.16)!important}.seatwise-nav-loading{visibility:visible}';document.head.appendChild(style);nav.classList.remove('seatwise-nav-loading');
})();
(function(){if(!document.querySelector('.saved-grid'))return;const s=document.createElement('style');s.textContent='.saved-grid{display:block!important}.saved-grid .class-card{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));margin:0 0 18px!important;width:100%}.saved-grid .class-head{grid-column:1/-1;width:100%}.saved-grid .section-row{min-width:0;border-bottom:1px solid #eef1f5;border-right:1px solid #eef1f5}.saved-grid .section-row:nth-child(3n){border-right:0}@media(max-width:1100px){.saved-grid .class-card{grid-template-columns:repeat(2,minmax(0,1fr))}.saved-grid .section-row:nth-child(3n){border-right:1px solid #eef1f5}.saved-grid .section-row:nth-child(2n){border-right:0}}@media(max-width:650px){.saved-grid .class-card{grid-template-columns:1fr}.saved-grid .section-row{border-right:0}}';document.head.appendChild(s)})();
document.addEventListener('DOMContentLoaded',initializeAcademicSessionUI);
