const SEATWISE_SUPABASE_URL = 'https://axhyzxuclxjojhtispqp.supabase.co';
const SEATWISE_SUPABASE_KEY = 'sb_publishable_6biluj5Hfmtz3tplDaO6qw_ektOIx3h';

const seatwiseDb = supabase.createClient(SEATWISE_SUPABASE_URL, SEATWISE_SUPABASE_KEY);
function setSeatwiseSession(user){sessionStorage.setItem('seatwiseUser',JSON.stringify({id:user.id,name:user.name,phone:user.phone}))}
function getSeatwiseSession(){try{const v=sessionStorage.getItem('seatwiseUser');return v?JSON.parse(v):null}catch(e){return null}}
function clearSeatwiseSession(){sessionStorage.removeItem('seatwiseUser');sessionStorage.removeItem('seatwiseAdmin')}
function requireSeatwiseLogin(){const user=getSeatwiseSession();if(!user){window.location.href='index.html';return null}return user}
async function logActivity(action,details={},userId=null){const user=getSeatwiseSession(),id=userId||user?.id||null;const{error}=await seatwiseDb.from('activity_logs').insert({user_id:id,action,details});if(error)console.error('Activity log error:',error)}
async function findAdminByPhone(phone){const normalizedPhone=phone.replace(/\D/g,'');return await seatwiseDb.from('admin_users').select('id,name,phone,pin,must_change_pin').eq('phone',normalizedPhone).maybeSingle()}
async function changeAdminPin(userId,newPin){return await seatwiseDb.from('admin_users').update({pin:newPin,must_change_pin:false}).eq('id',userId).select('id,name,phone,must_change_pin').single()}
function normalizePhone(value){return value.replace(/\D/g,'')}
function getCurrentAcademicSession(date=new Date()){const month=date.getMonth(),year=date.getFullYear(),startYear=month>=3?year:year-1;return `${startYear}-${startYear+1}`}
async function ensureCurrentAcademicSession(){const sessionName=getCurrentAcademicSession(),startYear=Number(sessionName.slice(0,4));const{error}=await seatwiseDb.from('academic_sessions').upsert({session_name:sessionName,start_date:`${startYear}-04-01`,end_date:`${startYear+1}-03-31`},{onConflict:'session_name'});if(error)console.error('Academic session error:',error);return sessionName}
async function initializeAcademicSessionUI(){const savedHead=document.querySelector('.saved-head');if(!savedHead)return;const sessionName=await ensureCurrentAcademicSession(),description=savedHead.querySelector('p');if(description)description.textContent=`Current Session: ${sessionName}`}
(function setupLoginPhoneKeypad(){function getInputs(){return Array.from(document.querySelectorAll('#loginPhoneDigits .phone-digit'))}function getValue(){return getInputs().map(i=>i.value).join('')}function addDigit(d){const inputs=getInputs(),i=inputs.findIndex(x=>!x.value);if(i===-1)return;inputs[i].value=d;if(i<inputs.length-1)inputs[i+1].focus();else document.querySelector('#pinContainer .pin-box')?.classList.add('ready')}function clear(){getInputs().forEach(i=>i.value='');getInputs()[0]?.focus()}document.addEventListener('click',e=>{const key=e.target.closest('.key[data-number]'),clr=e.target.closest('#clearButton');if(!key&&!clr)return;const phone=getValue();if(key&&phone.length<10){e.preventDefault();e.stopImmediatePropagation();addDigit(key.dataset.number)}else if(clr&&phone.length<10){e.preventDefault();e.stopImmediatePropagation();clear()}},true)})();
(function applySavedClassReferenceLayout(){if(!document.querySelector('.saved-grid'))return;const s=document.createElement('style');s.id='seatwise-saved-class-reference-layout';s.textContent='.saved-grid{display:block!important}.saved-grid .class-card{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr));margin:0 0 18px!important;width:100%}.saved-grid .class-card:last-child{margin-bottom:0!important}.saved-grid .class-head{grid-column:1/-1;width:100%}.saved-grid .section-row{min-width:0;border-bottom:1px solid #eef1f5;border-right:1px solid #eef1f5}.saved-grid .section-row:nth-child(3n){border-right:0}@media(max-width:1100px){.saved-grid .class-card{grid-template-columns:repeat(2,minmax(0,1fr))}.saved-grid .section-row:nth-child(3n){border-right:1px solid #eef1f5}.saved-grid .section-row:nth-child(2n){border-right:0}}@media(max-width:650px){.saved-grid .class-card{grid-template-columns:1fr}.saved-grid .section-row,.saved-grid .section-row:nth-child(2n),.saved-grid .section-row:nth-child(3n){border-right:0}}';document.head.appendChild(s)})();
(function initializeGlobalSidebar(){function apply(){const nav=document.querySelector('.nav');if(!nav)return;const file=(window.location.pathname.split('/').pop()||'index.html').toLowerCase();const items=[['dashboard.html','▦','Dashboard'],['students.html','♙','Classes & Sections'],['rooms.html','⌂','Rooms'],['subjects.html','◈','Subjects'],['exam-planner.html','◫','Exam Planner'],['#','▤','Exams'],['#','◧','Seating Plans'],['#','◷','History']];nav.innerHTML='<div class="nav-label">Main Menu</div>'+items.map(([href,icon,label])=>{const active=href!== '#'&&href===file?' class="active"':'';return `<a href="${href}"${active}><span class="nav-icon">${icon}</span>${label}</a>`}).join('')}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply()})();
document.addEventListener('DOMContentLoaded',initializeAcademicSessionUI);
